default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: root
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sreedev_development

test:
  <<: *default
  database: sreedev_test

production:
  <<: *default
  database: sreedev_production
  username: sreedev
  password: <%= ENV['SREEDEV_DATABASE_PASSWORD'] %>
